export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_NEW_PRODUCT = 'GET_NEW_PRODUCT';
export const GET_NEW_PRODUCT_SUCCESS = 'GET_NEW_PRODUCT_SUCCESS';
export const GET_NEW_PRODUCT_FAIL = 'GET_NEW_PRODUCT_FAIL';

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';
export const GET_DETAIL_PRODUCT_FAIL = 'GET_DETAIL_PRODUCT_FAIL';
